/* tslint:disable */
/* eslint-disable */
export const mount_workers: () => void;
export const unmount_workers: () => void;
export const mandel_generation: () => number;
export const mandel_height: () => number;
export const mandel_owner_ptr: () => number;
export const mandel_pixels_ptr: () => number;
export const mandel_render: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => number;
export const mandel_tile: () => number;
export const mandel_tiles_done: () => number;
export const mandel_tiles_total: () => number;
export const mandel_tiles_x: () => number;
export const mandel_width: () => number;
export const wasm_memory: () => any;
export const sched_idle: () => number;
export const sched_loads: () => [number, number];
export const sched_num_workers: () => number;
export const sched_waiting: () => number;
export const scheduler_inject: (a: number, b: number) => void;
export const init_hooks: () => void;
export const __notify_index: (a: number) => number;
export const __worker_drain: (a: number) => number;
export const wasm_bindgen_f183f172ff9cbd62___convert__closures_____invoke___wasm_bindgen_f183f172ff9cbd62___JsValue______true_: (a: number, b: number, c: any) => void;
export const wasm_bindgen_f183f172ff9cbd62___convert__closures_____invoke_______true_: (a: number, b: number) => void;
export const memory: WebAssembly.Memory;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __wbindgen_thread_destroy: (a?: number, b?: number, c?: number) => void;
export const __wbindgen_start: (a: number) => void;
